apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-exporter
  labels:
    app: nats-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-exporter
  template:
    metadata:
      labels:
        app: nats-exporter
    spec:
      containers:
        - name: nats-exporter
          image: natsio/prometheus-nats-exporter:latest
          ports:
            - containerPort: 7777
          command: ["/prometheus-nats-exporter"]
          args: ["-varz", "http://nats.default.svc.cluster.local:8222"]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-exporter
spec:
  type: NodePort
  selector:
    app: nats-exporter
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
    - name: dnsutils
      image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
