global:
  resolve_timeout: 3m
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  group_by: ["alertname"]
  group_wait: 1s
  group_interval: 3m
  repeat_interval: 5m
  receiver: "slack-notifications"
receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#local-server"
        send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
        http_config:
          tls_config:
            insecure_skip_verify: true
