global:
  resolve_timeout: 10m
route:
  group_by: ["alertname"]
  group_wait: 1s
  group_interval: 3m
  repeat_interval: 5m
  receiver: "slack-notifications"
receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#local-server"
        api_url: "https://hooks.slack.com/services/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"
