global:
  resolve_timeout: 10m
route:
  group_by: ["namespace"]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 4h
  receiver: "slack-notifications"
  routes:
    - match:
        alertname: Watchdog
    - match:
        app: amo
receivers:
  - name: "slack-notifications"
    webhook_configs:
      - url: https://2d9133a09ad2.ngrok.io/api/sendPrometheusAlertsToSlack
        send_resolved: true
