global:
  resolve_timeout: 10m
route:
  group_by: ["job"]
  group_wait: 30s
  group_interval: 30m
  repeat_interval: 12h
  receiver: "slack-notifications"
receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#dev-server"
        send_resolved: true
