global:
  resolve_timeout: 10m
route:
  group_by: ["job"]
  group_wait: 3m
  group_interval: 10m
  repeat_interval: 5m
  receiver: "slack-notifications"
receivers:
  - name: "slack-notifications"
    webhook_configs:
      - url: https://cea2ab31a857.ngrok.io/moon/api/sendPrometheusAlertsToSlack
        send_resolved: true
