global:
  resolve_timeout: 10m
route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 4h
  receiver: "null"
  routes:
    - receiver: "slack-notifications"
      match:
        alertname: CrashLooping
    - receiver: "slack-notifications"
      match:
        alertname: HighCpuUsage
receivers:
  - name: "null"
  - name: "slack-notifications"
    webhook_configs:
      - url: https://95540aa2c064.ngrok.io/api/sendPrometheusAlertsToSlack
        send_resolved: true
