groups:
  - name: custom-alert-rules
    rules:
      - alert: CrashLooping
        expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace="default"}[3m]) * 60 * 5 > 0
        for: 3m
        labels:
          app: amo
          severity: critical
        annotations:
          summary: Pod is crash looping.
          description: Pod {{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 10 minutes.
      - alert: HighCpuUsage
        expr: (sum(rate(container_cpu_usage_seconds_total{namespace="default"}[10m])) BY (namespace, pod) * 100) > 80
        for: 3m
        labels:
          app: amo
          severity: critical
        annotations:
          summary: Container CPU usage (pod {{ $labels.pod }})
          description: "Container CPU usage {{ $labels.pod }} is above 80%"
