apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 10m
      slack_api_url: "https://hooks.slack.com/services/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"
    route:
      group_by: ["job"]
      group_wait: 3m
      group_interval: 5m
      repeat_interval: 10m
      receiver: "slack-notifications"
    receivers:
      - name: "slack-notifications"
        slack_configs:
          - channel: "#local-server"
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
            text: |-
              {{ range .Alerts }}
                *Alert:* {{ .Labels.summary }}
                *Description:* {{ .Labels.description }}
                {{ end }}
              {{ end }}
type: Opaque
