apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 3m
      slack_api_url: "https://hooks.slack.com/services/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"
    route:
      group_by: ["alertname"]
      group_wait: 1s
      group_interval: 3m
      repeat_interval: 5m
      receiver: "slack-notifications"
    receivers:
      - name: "slack-notifications"
        slack_configs:
          - channel: "#local-server"
            send_resolved: true
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
            text: |-
              {{ range .Alerts }}
                *Alert:* {{ .Labels.summary }} - `{{ .Labels.severity }}`
                *Description:* {{ .Labels.description }}
                {{ end }}
              {{ end }}
            http_config:
              tls_config:
                insecure_skip_verify: true
type: Opaque
