apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 10m
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 5m
      receiver: "null"
      routes:
        - receiver: "slack-notifications"
          match:
            alertname: CrashLooping
        - receiver: "slack-notifications"
          match:
            alertname: HighCpuUsage
    receivers:
      - name: "null"
      - name: "slack-notifications"
        webhook_configs:
          - url: http://slack-notification.default.svc:9000/api/sendPrometheusAlertsToSlack
            send_resolved: true
type: Opaque
