apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 10m
    route:
      group_by: ["job"]
      group_wait: 30s
      group_interval: 3m
      repeat_interval: 1m
      receiver: "slack-notifications"
    receivers:
      - name: "slack-notifications"
        webhook_configs:
          - url: https://cea2ab31a857.ngrok.io/moon/api/sendPrometheusAlertsToSlack
            send_resolved: true
type: Opaque
